cmake_minimum_required(VERSION 4.0)
project(OppnGL LANGUAGES CXX)

set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${CMAKE_SOURCE_DIR}/bin/${CMAKE_BUILD_TYPE})

file(GLOB_RECURSE SOURCES
    "${CMAKE_CURRENT_SOURCE_DIR}/src/*.cpp"
)

add_executable(OppnGL ${SOURCES})

target_include_directories(OppnGL PRIVATE
	"${CMAKE_CURRENT_SOURCE_DIR}/Dependencies/GLFW/include"
	"${CMAKE_CURRENT_SOURCE_DIR}/Dependencies/GLEW/include"
	"${CMAKE_CURRENT_SOURCE_DIR}/include"
	"${CMAKE_CURRENT_SOURCE_DIR}/src/vendor"
	"${CMAKE_CURRENT_SOURCE_DIR}/src/tests"

)

target_link_directories(OppnGL PRIVATE
	"${CMAKE_CURRENT_SOURCE_DIR}/Dependencies/GLFW/lib-vc2022"
	"${CMAKE_CURRENT_SOURCE_DIR}/Dependencies/GLEW/lib/Release/x64"
)

target_link_libraries(OppnGL PRIVATE 
    glfw3
	opengl32
	glew32s
)

target_compile_definitions(OppnGL PRIVATE
	GLEW_STATIC
)

# A helper command
add_custom_command(TARGET OppnGL POST_BUILD
    COMMAND ${CMAKE_COMMAND} -E copy_directory
        "${CMAKE_CURRENT_SOURCE_DIR}/res"
        "$<TARGET_FILE_DIR:OppnGL>/res"
)

